"""Export the trained brain and the exact optimum for the browser.

    python -m flynance.export_web

Writes ``flynance/casino/brain-data.js``, which the casino page loads. The point
of this script is that the committed .js file is *reproducible*: it is generated
from ``flynance/results/fly_brain.npz`` rather than hand-maintained, so the page
can never silently drift away from the network it claims to be running.

Weights are rounded to 6 decimals to keep the file small. That rounding is
harmless: ``flynance/casino/verify_browser_brain.mjs`` replays every one of the
280 decision states through the JavaScript implementation and compares against
this one, and the rounding has never changed a single action.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from flynance import optimal as opt

PARAM_KEYS = ("W1", "b1", "W2", "b2", "W3", "b3")
DEFAULT_MODEL = Path(__file__).resolve().parent / "results" / "fly_brain.npz"
DEFAULT_OUT = Path(__file__).resolve().parent / "casino" / "brain-data.js"


def write_reference(model_path: Path, ref_path: Path) -> Path:
    """Dump Python's action probabilities for every state, for the JS cross-check."""
    from flynance.brain import FlyBlackjackBrain
    from flynance.encoding import preprocess_state

    brain = FlyBlackjackBrain.load(model_path)
    reference = {}
    for player_sum in range(4, 22):
        for upcard in range(1, 11):
            for ace in (0, 1):
                if ace and player_sum < 12:
                    continue  # a usable ace implies a total of at least 12
                probs = brain.policy(preprocess_state((player_sum, upcard, ace))[None, :])[0]
                reference[f"{player_sum}_{upcard}_{ace}"] = [
                    round(float(probs[0]), 6), round(float(probs[1]), 6)
                ]
    ref_path.parent.mkdir(parents=True, exist_ok=True)
    ref_path.write_text(json.dumps(reference, separators=(",", ":")))
    print(f"Wrote {ref_path} ({len(reference)} reference states)")
    return ref_path


def export(model_path: Path, out_path: Path, decimals: int = 6) -> Path:
    """Write the weights and the optimal policy as a browser-loadable JS file."""
    if not model_path.exists():
        raise SystemExit(
            f"No trained brain at {model_path}.\n"
            "Train one first:  python -m flynance.run_experiment --episodes 200000"
        )

    archive = np.load(model_path)
    # brain.save() namespaces parameters under 'param_' alongside Adam state.
    weights = {key: archive[f"param_{key}"] for key in PARAM_KEYS}
    total = sum(v.size for v in weights.values())

    flat = {k: [round(float(x), decimals) for x in v.ravel()] for k, v in weights.items()}
    solution = opt.solve()
    policy = {f"{s}_{u}_{a}": int(act) for (s, u, a), act in solution.policy.items()}

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        f"// Generated by flynance/export_web.py -- do not edit by hand.\n"
        f"// The actual trained fly brain: {total:,} weights from {model_path.name}.\n"
        f"// Verified against the Python implementation by "
        f"casino/verify_browser_brain.mjs.\n"
        "window.FLY_WEIGHTS = " + json.dumps(flat, separators=(",", ":")) + ";\n"
        "// Exact optimal hit/stand policy from dynamic programming (optimal.py).\n"
        "window.OPTIMAL_POLICY = " + json.dumps(policy, separators=(",", ":")) + ";\n"
        f"window.OPTIMAL_EV = {solution.expected_value:.6f};\n"
    )
    print(f"Wrote {out_path} ({out_path.stat().st_size:,} bytes): "
          f"{total:,} weights, {len(policy)} optimal decisions")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--decimals", type=int, default=6)
    parser.add_argument("--reference", type=Path, default=None,
                        help="also dump Python action probabilities for "
                             "verify_browser_brain.mjs to check against")
    args = parser.parse_args()
    export(args.model, args.out, args.decimals)
    if args.reference:
        write_reference(args.model, args.reference)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
